title: Freefy system status page
baseURL: 'https://status.freefy.online'
languageCode: es
params:
  copyrightHolder: Freefy
  dateFormat: 'January 2, 2006 at 3:04 PM'
  description_footer: >-
    Síguenos en Twitter para más información<a class='text-grey-darkest'
    title='@freefyonline' href='https://twitter.com/freefyonline'>Twitter</a>
    para más información.
  description_header: >-
    Information about <a class='text-grey-darkest' title='Visit example.com'
    href='https://www.example.com/'>example</a> systems operations.<br />Follow
    us <a class='text-grey-darkest' title='Visit our page on Twitter'
    href='https://www.twitter.com/example'>on Twitter</a> or subscribe to <a
    class='text-grey-darkest' href='%s' >RSS</a><br />to be alerted of new
    events.
  eventsPerPage: 10
  groups:
    - Servicios
  logo: 'https://freefy.online/images/freefy_logo_color.png'
  meta_description: >-
    This status page provides updated information about our systems normal
    operation, incidents that may happen and their resolution.
  shortDateFormat: '15:04 — Jan 2'
  systems:
    - description: Freefy app
      link: 'https://app.freefy.online'
      name: Web App
    - description: The official website
      link: 'https://freefy.online'
      name: Web
  timezoneString: ' UTC+2'
